all:
  hosts:
    server1:
      ansible_port: 22
      ansible_host: 192.168.1.100
      ansible_user: example_user
      ansible_ssh_pass: example_password
      ansible_become_pass: example_sudo_password
      ansible_python_interpreter: /usr/bin/python3
    server2:
      ansible_port: 22
      ansible_host: 192.168.1.101
      ansible_user: example_user2
      ansible_ssh_pass: example_password2
      ansible_become_pass: example_sudo_password2
      ansible_python_interpreter: /usr/bin/python3


        