sur:
  hosts:
    zojaji:
        ansible_port: 22
        ansible_host: 185.206.229.142
        ansible_user: deployer
        ansible_ssh_pass: sdSDKJH#(2349832LSKJ123!#%$#)  
        ansible_sudo_pass: hcylSEZJ9359
        ansible_python_interpreter: /usr/bin/python3
    explorer:
        ansible_port: 22
        ansible_host: 94.182.187.5
        ansible_user: root
        ansible_ssh_pass: nkjsDGDQ3538  
        ansible_sudo_pass: nkjsDGDQ3538
        ansible_python_interpreter: /usr/bin/python3   

        