all:
  hosts:
    server1:
        ansible_port: 22
        ansible_host: 192.168.1.101
        ansible_user: example_user2
        ansible_ssh_pass: example_password2
        ansible_become_pass: example_sudo_password2
        ansible_python_interpreter: /usr/bin/python3
    # local:
    #     ansible_connection: local
    #     ansible_user: user
    #     ansible_ssh_pass: pass
    #     ansible_sudo_pass: pass

        