---

- name: Create group
  become: yes
  group:
    name: docker
    state: present

- name: Ensure docker users are added to the docker group.
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"