---
# tasks file for webserver

- name: Make sure deployments directory exists
  file:
    path: /srv/deployments
    state: directory
    
- name: Make sure nginx config directory exists
  file:
    path: /srv/nginx/conf/
    state: directory

- name: Copy docker-compose file
  become: yes
  copy:
    src: docker-compose.yml
    dest: /srv/deployments/docker-compose.yml

- name: Copy nginx config file
  become: yes
  copy:
    src: nginx.conf
    dest: "/srv/nginx/conf/sur.conf"
    mode: 0766
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    
- name: Start docker container
  become: yes
  command: chdir=/srv/deployments/ docker-compose up -d --force-recreate

