---



- name: pull sur image
  become: yes
  shell: docker pull registry.surnet.org/sur:prod

- name: Re-create sur container
  become: yes
  docker_container:
    name: sur
    image: registry.surnet.org/sur:prod
    state: started
    restart_policy: always
    privileged: yes
    env:
      BESU_BOOTNODES: '{{sur1}}'
      BESU_P2P_HOST: 0.0.0.0
      BESU_MINER_ENABLED: "true"
      BESU_MINER_COINBASE: "0xbc2df8f82ead9b73b10efdb7a42fbaa0c763ff4a"
      BESU_RPC_HTTP_API: ETH,NET,IBFT,ADMIN,MINER
    restart: yes
    recreate: yes
    volumes:
      - "{{srv}}/docker:/opt/sur/externalVolume"
    networks:
      - name: "sur"
