---



- name: pull sur image
  become: yes
  shell: docker pull registry.surnet.org/sur:prod

- name: Re-create sur container
  become: yes
  docker_container:
    name: sur
    image: registry.surnet.org/sur:prod
    state: started
    restart_policy: always
    privileged: yes
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    env:
      BESU_BOOTNODES: "{{sur1}}"
      BESU_P2P_HOST: 0.0.0.0
      BESU_MINER_ENABLED: "true"
      BESU_MINER_COINBASE: "0x8a6ad97d00c13a5537c75a5076760f44619aec67"
      BESU_RPC_HTTP_API: ETH,NET,IBFT,ADMIN,MINER
      BESU_MIN_GAS_PRICE: "10000000000000"
    restart: yes
    recreate: yes
    volumes:
      - "{{srv}}/docker:/opt/sur/externalVolume"
    networks:
      - name: "sur"





# curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xd2b95b9ebf6f4511341f61d42d916cb6d32d5f81", "latest"],"id":53}' http://localhost:8545
# curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xd2b95b9ebf6f4511341f61d42d916cb6d32d5f81", "latest"],"id":53}' http://localhost:8545
# curl -X POST --data '{"jsonrpc":"2.0","method": "eth_getMinerDataByBlockNumber","params": ["0x3"],"id": 1}' http://127.0.0.1:8545