---
# tasks file for node deployment

- include: directories.yml
  tags: setup

- name: Capture files to delete  #TODO: Seperate this 
  find:
    paths: "{{srv}}/docker/data"
    file_type: directory
  register: found_files
  tags: remove-data

- name: Delete files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ found_files['files'] }}"
  tags: remove-data

- name: Copy genesis file
  become: yes
  copy:
    src: genesis.json
    dest: "{{ srv }}/docker/genesis.json"
    mode: 0766
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  tags: setup


- name: Copy toEncode file #TODO: Delete this
  become: yes
  copy:
    src: toEncode.json
    dest: "{{ srv }}/docker/toEncode.json"
    mode: 0766
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  tags: setup


- include: create_container.yml
  tags: restart, deploy

- include: extract_address.yml
  tags: address

- include: extract_enode_address.yml
  tags: address

- include: generate_extra_data.yml
  tags: extradata

- include: firewall.yml
  tags: firewall

# besu rlp encode --from=toEncode.json --type=IBFT_EXTRA_DATA