---

- name: clone templates repo
  become: yes
  git:
    repo: "https://{{git_user}}:{{git_token|urlencode()}}@{{ templates_repo }}"
    dest: "{{ confs }}"

- name: copy ssl privkey
  become: yes
  copy:
    src: privkey_rytika.pem
    dest: "{{certs}}/privkey.pem"

- name: copy ssl fullchain
  become: yes
  copy:
    src: fullchain_rytika.pem
    dest: "{{certs}}/fullchain.pem"